"""Regenerate frontend/lib/fixtures.ts from the responses the backend serves.

The frontend's locked fixtures are a mirror, not hand-written content: this
script boots the app hermetically (no .env, no vector store, no query log in
the working tree) and captures the three deterministic responses verbatim:

- demoAnalyzeResponse — the Demo answer for the canonical bank cloud outage
  Scenario (issue #54), driven exactly as the demo button drives it: the
  canonical id, description, and question over POST /api/analyze.
- notAvailableResponse — the Not-available reply Live mode serves while the
  vector store is un-ingested (backend/src/availability.py).
- demoNotAvailableResponse — the noop fallback a custom Scenario receives in
  Demo mode (backend/src/main.py, the non-canonical branch).

The Insufficient-evidence fixture is a hand-authored stand-in (a real one
needs an LLM planner), so the script re-uses whatever that export currently
holds instead of regenerating it: edit fixtures.ts for that one fixture, the
backend sources for everything else.

Run from the repository root:

    python backend/scripts/generate_frontend_fixtures.py
"""

import json
import os
import sys
from pathlib import Path
from tempfile import mkdtemp

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "backend"))
sys.path.insert(0, str(ROOT / "backend" / "tests"))

# The hermetic preamble, in conftest's order and for the same reasons: the
# root .env must be neutralised before src.config is first imported, and the
# query log must land outside the working tree.
import src.config as _config

_config._ENV_PATH = Path(mkdtemp()) / ".env"
os.environ["QUERY_LOG_PATH"] = str(Path(mkdtemp()) / "queries" / "queries.jsonl")
os.environ["OPENROUTER_API_KEY"] = "sk-or-fixture-not-a-real-key"

import src.availability as availability

# The boot probe and the Live availability gate both read the store; a
# hermetic zero keeps the script keyless and storeless.
availability.stored_chunk_count = lambda _database_url: 0

from conftest import (
    CANONICAL_SCENARIO_DESCRIPTION,
    CANONICAL_SCENARIO_ID,
    poll_progress,
)
from fastapi.testclient import TestClient

from src.eval_harness import LIVE_EVAL_SCENARIOS
from src.main import REQUEST_ID_HEADER, app

FIXTURES_PATH = ROOT / "frontend" / "lib" / "fixtures.ts"

HEADER = """\
// Generated by backend/scripts/generate_frontend_fixtures.py — the locked
// mirror of what the backend serves (issue #106). Do not edit by hand: the
// demo content and the Demo noop fallback live in backend/src/main.py, the
// Live-mode Not-available reply in backend/src/availability.py, and
// regenerating the file re-captures them.
// The one exception is insufficientEvidenceResponse, a hand-authored stand-in
// the script re-uses as-is — edit that fixture directly.
"""

DEMO_NOT_AVAILABLE_COMMENT = """\
// The Not-available response a custom Scenario receives in Demo mode: the
// canonical scenario is the only one Demo serves (ADR-0005), and the reply
// hints at the demo button (issue #48)."""

# The near-miss id the hand-typed canonical description would derive to — the
# realistic custom Scenario the noop fallback answers.
CUSTOM_SCENARIO_ID = "bank-relies-external-cloud-f27c7a6d"


def bank_scenario() -> dict:
    """The canonical demo payload: the bank case's authored content.

    The id and description come from the shared routing constants (conftest);
    the question from the bank case's eval record — with the description
    cross-checked so the two sources may never drift apart silently.
    """
    bank = next(s for s in LIVE_EVAL_SCENARIOS if s.scenario_id == CANONICAL_SCENARIO_ID)
    assert bank.description == CANONICAL_SCENARIO_DESCRIPTION
    return {
        "scenario": {
            "id": CANONICAL_SCENARIO_ID,
            "title": "Bank Cloud Outage",
            "description": CANONICAL_SCENARIO_DESCRIPTION,
        },
        "question": bank.question,
        "mode": "demo",
    }


def capture() -> tuple[dict, dict, dict]:
    """Boot the app and capture the three deterministic responses."""
    payload = bank_scenario()
    with TestClient(app) as client:
        demo = client.post(
            "/api/analyze",
            json=payload,
            headers={REQUEST_ID_HEADER: "fixture-demo"},
        )
        assert demo.status_code == 200, demo.text
        demo_noop = client.post(
            "/api/analyze",
            json={
                "scenario": {
                    "id": CUSTOM_SCENARIO_ID,
                    "description": CANONICAL_SCENARIO_DESCRIPTION,
                },
                "question": payload["question"],
                "mode": "demo",
            },
            headers={REQUEST_ID_HEADER: "fixture-noop"},
        )
        assert demo_noop.status_code == 200, demo_noop.text
        not_available = client.post(
            "/api/analyze",
            json={
                "scenario": {
                    "id": CUSTOM_SCENARIO_ID,
                    "description": CANONICAL_SCENARIO_DESCRIPTION,
                },
                "question": payload["question"],
                "mode": "live",
            },
            headers={REQUEST_ID_HEADER: "fixture-live"},
        )
        assert not_available.status_code == 200, not_available.text
        # A request-id-tagged Live submission runs in a background thread and
        # the POST returns a ProgressSnapshot — the answer arrives by polling,
        # exactly as the decoupled frontend client does.
        not_available = poll_progress(
            client,
            "fixture-live",
            lambda data: "trace" in data,
        )
        assert "trace" in not_available, not_available
    return demo.json(), demo_noop.json(), not_available


def current_insufficient_evidence() -> dict:
    """The hand-authored Insufficient-evidence fixture, re-used as-is."""
    source = FIXTURES_PATH.read_text(encoding="utf-8")
    marker = "export const insufficientEvidenceResponse: AnalyzeResponse = "
    start = source.index(marker) + len(marker)
    end = source.index("\n};\n", start)
    return json.loads(source[start:end] + "}")


def ts_export(name: str, data: dict) -> str:
    body = json.dumps(data, indent=2, ensure_ascii=True)
    return f"export const {name}: AnalyzeResponse = {body};\n"


def write_fixtures(demo: dict, demo_noop: dict, not_available: dict) -> None:
    parts = [
        HEADER,
        'import type { AnalyzeResponse } from "./contract";\n',
        ts_export("demoAnalyzeResponse", demo),
        ts_export("insufficientEvidenceResponse", current_insufficient_evidence()),
        ts_export("notAvailableResponse", not_available),
        f"{DEMO_NOT_AVAILABLE_COMMENT}\n{ts_export('demoNotAvailableResponse', demo_noop)}",
    ]
    FIXTURES_PATH.write_text("\n".join(parts), encoding="utf-8")


def main() -> None:
    demo, demo_noop, not_available = capture()
    write_fixtures(demo, demo_noop, not_available)
    print(f"Regenerated {FIXTURES_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
