// Generated by backend/scripts/generate_frontend_fixtures.py — the locked
// mirror of what the backend serves (issue #106). Do not edit by hand: the
// demo content and the Demo noop fallback live in backend/src/main.py, the
// Live-mode Not-available reply in backend/src/availability.py, and
// regenerating the file re-captures them.
// The one exception is insufficientEvidenceResponse, a hand-authored stand-in
// the script re-uses as-is — edit that fixture directly.

import type { AnalyzeResponse } from "./contract";

export const demoAnalyzeResponse: AnalyzeResponse = {
  "answer": {
    "findings": [
      {
        "statement": "The bank must run the outage through its ICT incident-management process, classify it by clients affected, duration, data losses, service criticality and economic impact and, once classified major, submit initial, intermediate and final reports within the harmonised time limits while promptly informing affected clients about the incident and mitigation measures.",
        "strength": "strong",
        "citations": [
          {
            "source_id": "dora",
            "source_short_name": "DORA",
            "article_number": 17,
            "recital_number": null,
            "annex_number": null,
            "section": "ICT-related incident management, classification and reporting",
            "provision": "Article 17",
            "quote": "Financial entities shall define, establish and implement an ICT-related incident management process to detect, manage and notify ICT-related incidents. Financial entities shall record all ICT-related incidents and significant cyber threats. Financial entities shall establish appropriate procedures a...",
            "relevance": null,
            "strength": null
          },
          {
            "source_id": "dora",
            "source_short_name": "DORA",
            "article_number": 18,
            "recital_number": null,
            "annex_number": null,
            "section": "ICT-related incident management, classification and reporting",
            "provision": "Article 18",
            "quote": "Financial entities shall classify ICT-related incidents and shall determine their impact based on the following criteria: Financial entities shall classify cyber threats as significant based on the criticality of the services at risk, including the financial entity's transactions and operations, num...",
            "relevance": null,
            "strength": null
          },
          {
            "source_id": "dora",
            "source_short_name": "DORA",
            "article_number": 19,
            "recital_number": null,
            "annex_number": null,
            "section": "ICT-related incident management, classification and reporting",
            "provision": "Article 19",
            "quote": "Financial entities shall report major ICT-related incidents to the relevant competent authority as referred to in Article 46 in accordance with paragraph 4 of this Article. Where a financial entity is subject to supervision by more than one national competent authority referred to in Article 46, Mem...",
            "relevance": null,
            "strength": null
          }
        ]
      },
      {
        "statement": "The bank must activate business continuity plans that prioritise resuming the critical online-banking function - plans that cover functions outsourced to the cloud provider - and restore from backups and restoration capabilities.",
        "strength": "strong",
        "citations": [
          {
            "source_id": "dora",
            "source_short_name": "DORA",
            "article_number": 11,
            "recital_number": null,
            "annex_number": null,
            "section": "ICT risk management",
            "provision": "Article 11",
            "quote": "As part of the ICT risk management framework referred to in Article 6(1) and based on the identification requirements set out in Article 8, financial entities shall put in place a comprehensive ICT business continuity policy, which may be adopted as a dedicated specific policy, forming an integral p...",
            "relevance": null,
            "strength": null
          },
          {
            "source_id": "dora",
            "source_short_name": "DORA",
            "article_number": 12,
            "recital_number": null,
            "annex_number": null,
            "section": "ICT risk management",
            "provision": "Article 12",
            "quote": "For the purpose of ensuring the restoration of ICT systems and data with minimum downtime, limited disruption and loss, as part of their ICT risk management framework, financial entities shall develop and document: Financial entities shall set up backup systems that can be activated in accordance wi...",
            "relevance": null,
            "strength": null
          }
        ]
      },
      {
        "statement": "Client personal data must remain protected and available: the bank owes security measures and timely restoration of access after the technical incident under the GDPR's integrity and confidentiality baseline, with the recovery and notification processing resting on a lawful basis and the measures implemented and demonstrable.",
        "strength": "strong",
        "citations": [
          {
            "source_id": "gdpr",
            "source_short_name": "GDPR",
            "article_number": 32,
            "recital_number": null,
            "annex_number": null,
            "section": "Security of Personal Data",
            "provision": "Article 32",
            "quote": "Taking into account the state of the art, the costs of implementation and the nature, scope, context and purposes of processing as well as the risk of varying likelihood and severity for the rights and freedoms of natural persons, the controller and the processor shall implement appropriate technica...",
            "relevance": null,
            "strength": null
          },
          {
            "source_id": "gdpr",
            "source_short_name": "GDPR",
            "article_number": 5,
            "recital_number": null,
            "annex_number": null,
            "section": "Principles",
            "provision": "Article 5",
            "quote": "Personal data shall be: (a) processed lawfully, fairly and in a transparent manner in relation to the data subject ('lawfulness, fairness and transparency'); (b) collected for specified, explicit and legitimate purposes and not further processed in a manner that is incompatible with those purposes; ...",
            "relevance": null,
            "strength": null
          },
          {
            "source_id": "gdpr",
            "source_short_name": "GDPR",
            "article_number": 6,
            "recital_number": null,
            "annex_number": null,
            "section": "Principles",
            "provision": "Article 6",
            "quote": "Processing shall be lawful only if and to the extent that at least one of the following applies: (a) the data subject has given consent to the processing of his or her personal data for one or more specific purposes; (b) processing is necessary for the performance of a contract to which the data sub...",
            "relevance": null,
            "strength": null
          },
          {
            "source_id": "gdpr",
            "source_short_name": "GDPR",
            "article_number": 24,
            "recital_number": null,
            "annex_number": null,
            "section": "General Obligations",
            "provision": "Article 24",
            "quote": "Taking into account the nature, scope, context and purposes of processing as well as the risks of varying likelihood and severity for the rights and freedoms of natural persons, the controller shall implement appropriate technical and organisational measures to ensure and to be able to demonstrate t...",
            "relevance": null,
            "strength": null
          }
        ]
      },
      {
        "statement": "In hosting and processing the bank's customer data on the disrupted systems, the cloud provider acts as a processor: the bank may engage it only under a contract carrying Article 28(3)'s guarantees, and the provider must assist the bank in meeting its security and breach-response obligations.",
        "strength": "strong",
        "citations": [
          {
            "source_id": "gdpr",
            "source_short_name": "GDPR",
            "article_number": 28,
            "recital_number": null,
            "annex_number": null,
            "section": "General Obligations",
            "provision": "Article 28",
            "quote": "Where processing is to be carried out on behalf of a controller, the controller shall use only processors providing sufficient guarantees to implement appropriate technical and organisational measures in such a manner that processing will meet the requirements of this Regulation and ensure the prote...",
            "relevance": null,
            "strength": null
          }
        ]
      },
      {
        "statement": "The bank must identify and document the processes dependent on the cloud provider and its interconnections, keeping those inventories updated - the identification step grounding the recovery and third-party analysis.",
        "strength": "strong",
        "citations": [
          {
            "source_id": "dora",
            "source_short_name": "DORA",
            "article_number": 8,
            "recital_number": null,
            "annex_number": null,
            "section": "ICT risk management",
            "provision": "Article 8",
            "quote": "As part of the ICT risk management framework referred to in Article 6(1), financial entities shall identify, classify and adequately document all ICT supported business functions, roles and responsibilities, the information assets and ICT assets supporting those functions, and their roles and depend...",
            "relevance": null,
            "strength": null
          }
        ]
      },
      {
        "statement": "The bank's management body must approve, oversee and periodically review the ICT business continuity policy and the response and recovery plans the outage engages and the post-incident revisions produce.",
        "strength": "strong",
        "citations": [
          {
            "source_id": "dora",
            "source_short_name": "DORA",
            "article_number": 5,
            "recital_number": null,
            "annex_number": null,
            "section": "ICT risk management",
            "provision": "Article 5",
            "quote": "Financial entities shall have in place an internal governance and control framework that ensures an effective and prudent management of ICT risk, in accordance with Article 6(4), in order to achieve a high level of digital operational resilience. The management body of the financial entity shall def...",
            "relevance": null,
            "strength": null
          }
        ]
      },
      {
        "statement": "The bank must operate detection mechanisms that promptly surface anomalous activities and ICT-related incidents across its ICT systems.",
        "strength": "strong",
        "citations": [
          {
            "source_id": "dora",
            "source_short_name": "DORA",
            "article_number": 10,
            "recital_number": null,
            "annex_number": null,
            "section": "ICT risk management",
            "provision": "Article 10",
            "quote": "Financial entities shall have in place mechanisms to promptly detect anomalous activities, in accordance with Article 17, including ICT network performance issues and ICT-related incidents, and to identify potential material single points of failure. All detection mechanisms referred to in the first...",
            "relevance": null,
            "strength": null
          }
        ]
      },
      {
        "statement": "The recovery processing must appear in the bank's records of processing activities, covering purposes, categories of data subjects and personal data, recipients including the cloud provider, and the security measures.",
        "strength": "strong",
        "citations": [
          {
            "source_id": "gdpr",
            "source_short_name": "GDPR",
            "article_number": 30,
            "recital_number": null,
            "annex_number": null,
            "section": "General Obligations",
            "provision": "Article 30",
            "quote": "Each controller and, where applicable, the controller's representative, shall maintain a record of processing activities under its responsibility. That record shall contain all of the following information: (a) the name and contact details of the controller and, where applicable, the joint controlle...",
            "relevance": null,
            "strength": null
          }
        ]
      },
      {
        "statement": "As a credit institution the bank falls within DORA, and the cloud failure is an ICT-related incident affecting a critical function supplied by an ICT third-party service provider, with the response scaled to the bank's size and risk profile.",
        "strength": "moderate",
        "citations": [
          {
            "source_id": "dora",
            "source_short_name": "DORA",
            "article_number": 2,
            "recital_number": null,
            "annex_number": null,
            "section": "General provisions",
            "provision": "Article 2",
            "quote": "Without prejudice to paragraphs 3 and 4, this Regulation applies to the following entities: For the purposes of this Regulation, entities referred to in paragraph 1, points (a) to (t), shall collectively be referred to as 'financial entities'. This Regulation does not apply to: Member States may exc...",
            "relevance": null,
            "strength": null
          },
          {
            "source_id": "dora",
            "source_short_name": "DORA",
            "article_number": 3,
            "recital_number": null,
            "annex_number": null,
            "section": "General provisions",
            "provision": "Article 3",
            "quote": "For the purposes of this Regulation, the following definitions shall apply:",
            "relevance": null,
            "strength": null
          },
          {
            "source_id": "dora",
            "source_short_name": "DORA",
            "article_number": 4,
            "recital_number": null,
            "annex_number": null,
            "section": "General provisions",
            "provision": "Article 4",
            "quote": "Financial entities shall implement the rules laid down in Chapter II in accordance with the principle of proportionality, taking into account their size and overall risk profile, and the nature, scale and complexity of their services, activities and operations. In addition, the application by financ...",
            "relevance": null,
            "strength": null
          }
        ]
      },
      {
        "statement": "The major incident triggers a review of the ICT risk-management framework and a post-incident review of the outage's causes and the response's effectiveness, with a communication strategy framing what clients and stakeholders are told.",
        "strength": "moderate",
        "citations": [
          {
            "source_id": "dora",
            "source_short_name": "DORA",
            "article_number": 6,
            "recital_number": null,
            "annex_number": null,
            "section": "ICT risk management",
            "provision": "Article 6",
            "quote": "Financial entities shall have a sound, comprehensive and well-documented ICT risk management framework as part of their overall risk management system, which enables them to address ICT risk quickly, efficiently and comprehensively and to ensure a high level of digital operational resilience. The IC...",
            "relevance": null,
            "strength": null
          },
          {
            "source_id": "dora",
            "source_short_name": "DORA",
            "article_number": 13,
            "recital_number": null,
            "annex_number": null,
            "section": "ICT risk management",
            "provision": "Article 13",
            "quote": "Financial entities shall have in place capabilities and staff to gather information on vulnerabilities and cyber threats, ICT-related incidents, in particular cyber-attacks, and analyse the impact they are likely to have on their digital operational resilience. Financial entities shall put in place ...",
            "relevance": null,
            "strength": null
          },
          {
            "source_id": "dora",
            "source_short_name": "DORA",
            "article_number": 14,
            "recital_number": null,
            "annex_number": null,
            "section": "ICT risk management",
            "provision": "Article 14",
            "quote": "As part of the ICT risk management framework referred to in Article 6(1), financial entities shall have in place crisis communication plans enabling a responsible disclosure of, at least, major ICT-related incidents or vulnerabilities to clients and counterparts as well as to the public, as appropri...",
            "relevance": null,
            "strength": null
          }
        ]
      },
      {
        "statement": "The bank stays fully responsible for DORA compliance despite the provider's failure and any supervisory feedback on its reports; its dependence on a single cloud provider requires concentration-risk analysis and substitutability considerations, and the contract must secure incident assistance, notification of material developments and tested contingency plans, with audit, termination and exit-strategy levers.",
        "strength": "moderate",
        "citations": [
          {
            "source_id": "dora",
            "source_short_name": "DORA",
            "article_number": 28,
            "recital_number": null,
            "annex_number": null,
            "section": "Managing of ICT third-party risk",
            "provision": "Article 28",
            "quote": "Financial entities shall manage ICT third-party risk as an integral component of ICT risk within their ICT risk management framework as referred to in Article 6(1), and in accordance with the following principles: As part of their ICT risk management framework, financial entities, other than entitie...",
            "relevance": null,
            "strength": null
          },
          {
            "source_id": "dora",
            "source_short_name": "DORA",
            "article_number": 29,
            "recital_number": null,
            "annex_number": null,
            "section": "Managing of ICT third-party risk",
            "provision": "Article 29",
            "quote": "When performing the identification and assessment of risks referred to in Article 28(4), point (c), financial entities shall also take into account whether the envisaged conclusion of a contractual arrangement in relation to ICT services supporting critical or important functions would lead to any o...",
            "relevance": null,
            "strength": null
          },
          {
            "source_id": "dora",
            "source_short_name": "DORA",
            "article_number": 30,
            "recital_number": null,
            "annex_number": null,
            "section": "Managing of ICT third-party risk",
            "provision": "Article 30",
            "quote": "The rights and obligations of the financial entity and of the ICT third-party service provider shall be clearly allocated and set out in writing. The full contract shall include the service level agreements and be documented in one written document which shall be available to the parties on paper, o...",
            "relevance": null,
            "strength": null
          },
          {
            "source_id": "dora",
            "source_short_name": "DORA",
            "article_number": 22,
            "recital_number": null,
            "annex_number": null,
            "section": "ICT-related incident management, classification and reporting",
            "provision": "Article 22",
            "quote": "Without prejudice to the technical input, advice or remedies and subsequent follow-up which may be provided, where applicable, in accordance with national law, by the CSIRTs under Directive (EU) 2022/2555, the competent authority shall, upon receipt of the initial notification and of each report as ...",
            "relevance": null,
            "strength": null
          }
        ]
      },
      {
        "statement": "If the outage investigation reveals a personal data breach, the 72-hour supervisory-authority notification and, where customers face high risk, the communication duty come into play alongside the DORA reporting, with the authority's corrective powers - from ordering communication to fines - behind that track.",
        "strength": "moderate",
        "citations": [
          {
            "source_id": "gdpr",
            "source_short_name": "GDPR",
            "article_number": 4,
            "recital_number": null,
            "annex_number": null,
            "section": "General Provisions",
            "provision": "Article 4",
            "quote": "For the purposes of this Regulation:",
            "relevance": null,
            "strength": null
          },
          {
            "source_id": "gdpr",
            "source_short_name": "GDPR",
            "article_number": 33,
            "recital_number": null,
            "annex_number": null,
            "section": "Security of Personal Data",
            "provision": "Article 33",
            "quote": "In the case of a personal data breach, the controller shall without undue delay and, where feasible, not later than 72 hours after having become aware of it, notify the personal data breach to the supervisory authority competent in accordance with Article 55, unless the personal data breach is unlik...",
            "relevance": null,
            "strength": null
          },
          {
            "source_id": "gdpr",
            "source_short_name": "GDPR",
            "article_number": 34,
            "recital_number": null,
            "annex_number": null,
            "section": "Security of Personal Data",
            "provision": "Article 34",
            "quote": "When the personal data breach is likely to result in a high risk to the rights and freedoms of natural persons, the controller shall communicate the personal data breach to the data subject without undue delay. The communication to the data subject referred to in paragraph 1 of this Article shall de...",
            "relevance": null,
            "strength": null
          },
          {
            "source_id": "gdpr",
            "source_short_name": "GDPR",
            "article_number": 58,
            "recital_number": null,
            "annex_number": null,
            "section": "Competence, Tasks and Powers",
            "provision": "Article 58",
            "quote": "Each supervisory authority shall have all of the following investigative powers: Each supervisory authority shall have all of the following corrective powers: Each supervisory authority shall have all of the following authorisation and advisory powers: The exercise of the powers conferred on the sup...",
            "relevance": null,
            "strength": null
          }
        ]
      },
      {
        "statement": "As a credit institution the bank cannot use the simplified ICT risk-management framework and must comply with the general framework of Articles 5 to 15.",
        "strength": "moderate",
        "citations": [
          {
            "source_id": "dora",
            "source_short_name": "DORA",
            "article_number": 16,
            "recital_number": null,
            "annex_number": null,
            "section": "ICT risk management",
            "provision": "Article 16",
            "quote": "Articles 5 to 15 of this Regulation shall not apply to small and non-interconnected investment firms, payment institutions exempted pursuant to Directive (EU) 2015/2366; institutions exempted pursuant to Directive 2013/36/EU in respect of which Member States have decided not to apply the option refe...",
            "relevance": null,
            "strength": null
          }
        ]
      }
    ],
    "actions": [
      "Have a qualified professional determine whether the outage is a major ICT-related incident under DORA Article 18, since the initial, intermediate, and final reporting duties (Article 19) turn on that classification.",
      "Have a qualified professional assess whether the outage investigation reveals a personal data breach, which would start the GDPR's 72-hour notification (Article 33) and, where customers face high risk, the communication duty (Article 34) alongside the DORA reporting.",
      "Have a qualified professional verify that affected clients are promptly informed about the incident and the mitigation measures (DORA Article 19(3); GDPR Article 34).",
      "Have a qualified professional review the concentration-risk analysis for the bank's dependence on a single cloud provider, including substitutability and alternative solutions (DORA Article 29).",
      "Have a qualified professional confirm that the cloud contract secures incident assistance, notification of material developments, and tested contingency plans, and that the audit, termination, and exit-strategy levers remain usable (DORA Articles 28 and 30).",
      "Have a qualified legal professional verify these findings against the company's actual situation before acting on them."
    ],
    "citations": [
      {
        "source_id": "dora",
        "source_short_name": "DORA",
        "article_number": 17,
        "recital_number": null,
        "annex_number": null,
        "section": "ICT-related incident management, classification and reporting",
        "provision": "Article 17",
        "quote": "Financial entities shall define, establish and implement an ICT-related incident management process to detect, manage and notify ICT-related incidents. Financial entities shall record all ICT-related incidents and significant cyber threats. Financial entities shall establish appropriate procedures a...",
        "relevance": "Article 17 obliges the bank to run the outage through its ICT incident-management process of detection, management, notification, escalation to senior management, and response procedures for timely restoration.",
        "strength": "strong"
      },
      {
        "source_id": "dora",
        "source_short_name": "DORA",
        "article_number": 18,
        "recital_number": null,
        "annex_number": null,
        "section": "ICT-related incident management, classification and reporting",
        "provision": "Article 18",
        "quote": "Financial entities shall classify ICT-related incidents and shall determine their impact based on the following criteria: Financial entities shall classify cyber threats as significant based on the criticality of the services at risk, including the financial entity's transactions and operations, num...",
        "relevance": "Article 18(1) requires the bank to classify the outage by clients affected, duration, data losses, service criticality, and economic impact, which determines whether the major-incident reporting duty is triggered.",
        "strength": "strong"
      },
      {
        "source_id": "dora",
        "source_short_name": "DORA",
        "article_number": 19,
        "recital_number": null,
        "annex_number": null,
        "section": "ICT-related incident management, classification and reporting",
        "provision": "Article 19",
        "quote": "Financial entities shall report major ICT-related incidents to the relevant competent authority as referred to in Article 46 in accordance with paragraph 4 of this Article. Where a financial entity is subject to supervision by more than one national competent authority referred to in Article 46, Mem...",
        "relevance": "Article 19 obliges the bank, once the outage is classified major, to submit initial, intermediate, and final reports to the competent authority and to promptly inform affected clients about the incident and mitigation measures.",
        "strength": "strong"
      },
      {
        "source_id": "dora",
        "source_short_name": "DORA",
        "article_number": 11,
        "recital_number": null,
        "annex_number": null,
        "section": "ICT risk management",
        "provision": "Article 11",
        "quote": "As part of the ICT risk management framework referred to in Article 6(1) and based on the identification requirements set out in Article 8, financial entities shall put in place a comprehensive ICT business continuity policy, which may be adopted as a dedicated specific policy, forming an integral p...",
        "relevance": "Article 11 obliges the bank to activate ICT business continuity and response plans that prioritise resumption of the critical online-banking function, and Article 11(4) requires those plans to cover functions outsourced through ICT third-party providers like the cloud host.",
        "strength": "moderate"
      },
      {
        "source_id": "dora",
        "source_short_name": "DORA",
        "article_number": 12,
        "recital_number": null,
        "annex_number": null,
        "section": "ICT risk management",
        "provision": "Article 12",
        "quote": "For the purpose of ensuring the restoration of ICT systems and data with minimum downtime, limited disruption and loss, as part of their ICT risk management framework, financial entities shall develop and document: Financial entities shall set up backup systems that can be activated in accordance wi...",
        "relevance": "Article 12's backup and restoration duties frame the recovery actions the bank invokes to bring online banking back within acceptable downtime.",
        "strength": "weak"
      },
      {
        "source_id": "gdpr",
        "source_short_name": "GDPR",
        "article_number": 32,
        "recital_number": null,
        "annex_number": null,
        "section": "Security of Personal Data",
        "provision": "Article 32",
        "quote": "Taking into account the state of the art, the costs of implementation and the nature, scope, context and purposes of processing as well as the risk of varying likelihood and severity for the rights and freedoms of natural persons, the controller and the processor shall implement appropriate technica...",
        "relevance": "Article 32(1)(b)-(c) obliges the bank to ensure availability of its processing systems and timely restoration of access to client personal data after the technical incident, running in parallel with DORA's recovery duties.",
        "strength": "moderate"
      },
      {
        "source_id": "gdpr",
        "source_short_name": "GDPR",
        "article_number": 5,
        "recital_number": null,
        "annex_number": null,
        "section": "Principles",
        "provision": "Article 5",
        "quote": "Personal data shall be: (a) processed lawfully, fairly and in a transparent manner in relation to the data subject ('lawfulness, fairness and transparency'); (b) collected for specified, explicit and legitimate purposes and not further processed in a manner that is incompatible with those purposes; ...",
        "relevance": "Article 5(1)(f)'s integrity-and-confidentiality principle grounds the bank's ongoing duty to protect client personal data processed through the disrupted systems.",
        "strength": "weak"
      },
      {
        "source_id": "gdpr",
        "source_short_name": "GDPR",
        "article_number": 6,
        "recital_number": null,
        "annex_number": null,
        "section": "Principles",
        "provision": "Article 6",
        "quote": "Processing shall be lawful only if and to the extent that at least one of the following applies: (a) the data subject has given consent to the processing of his or her personal data for one or more specific purposes; (b) processing is necessary for the performance of a contract to which the data sub...",
        "relevance": "Article 6 requires the recovery and notification processing of customer data to rest on a lawful basis, the lawfulness frame alongside the Article 5 principles for the breach response.",
        "strength": "weak"
      },
      {
        "source_id": "gdpr",
        "source_short_name": "GDPR",
        "article_number": 24,
        "recital_number": null,
        "annex_number": null,
        "section": "General Obligations",
        "provision": "Article 24",
        "quote": "Taking into account the nature, scope, context and purposes of processing as well as the risks of varying likelihood and severity for the rights and freedoms of natural persons, the controller shall implement appropriate technical and organisational measures to ensure and to be able to demonstrate t...",
        "relevance": "Article 24 obliges the bank to implement and demonstrate measures that keep processing compliant, framing the recovery and accountability follow-up the outage response must include.",
        "strength": "weak"
      },
      {
        "source_id": "gdpr",
        "source_short_name": "GDPR",
        "article_number": 28,
        "recital_number": null,
        "annex_number": null,
        "section": "General Obligations",
        "provision": "Article 28",
        "quote": "Where processing is to be carried out on behalf of a controller, the controller shall use only processors providing sufficient guarantees to implement appropriate technical and organisational measures in such a manner that processing will meet the requirements of this Regulation and ensure the prote...",
        "relevance": "Article 28 obliges the bank to engage the cloud host only as a processor under a contract carrying Article 28(3)'s guarantees, with Article 28(3)(f) requiring the provider's assistance with the breach and security duties, the GDPR counterpart to the DORA contract levers.",
        "strength": "moderate"
      },
      {
        "source_id": "dora",
        "source_short_name": "DORA",
        "article_number": 8,
        "recital_number": null,
        "annex_number": null,
        "section": "ICT risk management",
        "provision": "Article 8",
        "quote": "As part of the ICT risk management framework referred to in Article 6(1), financial entities shall identify, classify and adequately document all ICT supported business functions, roles and responsibilities, the information assets and ICT assets supporting those functions, and their roles and depend...",
        "relevance": "Article 8 requires the bank to identify and document all processes dependent on the cloud provider and their interconnections, the classification grounding the criticality and recovery analysis for the disrupted functions.",
        "strength": "weak"
      },
      {
        "source_id": "dora",
        "source_short_name": "DORA",
        "article_number": 5,
        "recital_number": null,
        "annex_number": null,
        "section": "ICT risk management",
        "provision": "Article 5",
        "quote": "Financial entities shall have in place an internal governance and control framework that ensures an effective and prudent management of ICT risk, in accordance with Article 6(4), in order to achieve a high level of digital operational resilience. The management body of the financial entity shall def...",
        "relevance": "Article 5 places the management body over the outage response: it must approve, oversee, and periodically review the ICT business continuity policy and the response and recovery plans the incident engages.",
        "strength": "weak"
      },
      {
        "source_id": "dora",
        "source_short_name": "DORA",
        "article_number": 10,
        "recital_number": null,
        "annex_number": null,
        "section": "ICT risk management",
        "provision": "Article 10",
        "quote": "Financial entities shall have in place mechanisms to promptly detect anomalous activities, in accordance with Article 17, including ICT network performance issues and ICT-related incidents, and to identify potential material single points of failure. All detection mechanisms referred to in the first...",
        "relevance": "Article 10 obliges the bank to operate detection mechanisms that promptly surface anomalous activities and ICT-related incidents, the capability the outage's arrival tested.",
        "strength": "weak"
      },
      {
        "source_id": "gdpr",
        "source_short_name": "GDPR",
        "article_number": 30,
        "recital_number": null,
        "annex_number": null,
        "section": "General Obligations",
        "provision": "Article 30",
        "quote": "Each controller and, where applicable, the controller's representative, shall maintain a record of processing activities under its responsibility. That record shall contain all of the following information: (a) the name and contact details of the controller and, where applicable, the joint controlle...",
        "relevance": "Article 30 requires the recovery processing to appear in the bank's records of activities, covering purposes, categories of data subjects and personal data, recipients including the cloud provider, and the security measures.",
        "strength": "weak"
      },
      {
        "source_id": "dora",
        "source_short_name": "DORA",
        "article_number": 2,
        "recital_number": null,
        "annex_number": null,
        "section": "General provisions",
        "provision": "Article 2",
        "quote": "Without prejudice to paragraphs 3 and 4, this Regulation applies to the following entities: For the purposes of this Regulation, entities referred to in paragraph 1, points (a) to (t), shall collectively be referred to as 'financial entities'. This Regulation does not apply to: Member States may exc...",
        "relevance": "Article 2(1)(a) brings the bank within DORA as a credit institution, engaging the ICT incident-management and third-party regimes that govern the outage response.",
        "strength": "moderate"
      },
      {
        "source_id": "dora",
        "source_short_name": "DORA",
        "article_number": 3,
        "recital_number": null,
        "annex_number": null,
        "section": "General provisions",
        "provision": "Article 3",
        "quote": "For the purposes of this Regulation, the following definitions shall apply:",
        "relevance": "Article 3's definitions of ICT-related incident, major incident, ICT third-party service provider, and critical or important function establish that the cloud failure is an ICT incident affecting a critical function supplied by an external provider.",
        "strength": "moderate"
      },
      {
        "source_id": "dora",
        "source_short_name": "DORA",
        "article_number": 4,
        "recital_number": null,
        "annex_number": null,
        "section": "General provisions",
        "provision": "Article 4",
        "quote": "Financial entities shall implement the rules laid down in Chapter II in accordance with the principle of proportionality, taking into account their size and overall risk profile, and the nature, scale and complexity of their services, activities and operations. In addition, the application by financ...",
        "relevance": "Article 4 scales the bank's incident-response and third-party obligations to its size and risk profile, the proportionality lens applied across the analysis.",
        "strength": "weak"
      },
      {
        "source_id": "dora",
        "source_short_name": "DORA",
        "article_number": 6,
        "recital_number": null,
        "annex_number": null,
        "section": "ICT risk management",
        "provision": "Article 6",
        "quote": "Financial entities shall have a sound, comprehensive and well-documented ICT risk management framework as part of their overall risk management system, which enables them to address ICT risk quickly, efficiently and comprehensively and to ensure a high level of digital operational resilience. The IC...",
        "relevance": "Article 6(5) makes a major incident a mandatory trigger for reviewing the bank's ICT risk-management framework, alongside the recovery itself.",
        "strength": "weak"
      },
      {
        "source_id": "dora",
        "source_short_name": "DORA",
        "article_number": 13,
        "recital_number": null,
        "annex_number": null,
        "section": "ICT risk management",
        "provision": "Article 13",
        "quote": "Financial entities shall have in place capabilities and staff to gather information on vulnerabilities and cyber threats, ICT-related incidents, in particular cyber-attacks, and analyse the impact they are likely to have on their digital operational resilience. Financial entities shall put in place ...",
        "relevance": "Article 13(2) requires a post-incident review of the outage's causes and of the effectiveness of the bank's response once the incident has disrupted core activities.",
        "strength": "weak"
      },
      {
        "source_id": "dora",
        "source_short_name": "DORA",
        "article_number": 14,
        "recital_number": null,
        "annex_number": null,
        "section": "ICT risk management",
        "provision": "Article 14",
        "quote": "As part of the ICT risk management framework referred to in Article 6(1), financial entities shall have in place crisis communication plans enabling a responsible disclosure of, at least, major ICT-related incidents or vulnerabilities to clients and counterparts as well as to the public, as appropri...",
        "relevance": "Article 14's communication-strategy duty frames how the bank informs clients and stakeholders about the outage, complementing the specific client-notification duty in Article 19(3).",
        "strength": "weak"
      },
      {
        "source_id": "dora",
        "source_short_name": "DORA",
        "article_number": 28,
        "recital_number": null,
        "annex_number": null,
        "section": "Managing of ICT third-party risk",
        "provision": "Article 28",
        "quote": "Financial entities shall manage ICT third-party risk as an integral component of ICT risk within their ICT risk management framework as referred to in Article 6(1), and in accordance with the following principles: As part of their ICT risk management framework, financial entities, other than entitie...",
        "relevance": "Article 28 keeps the bank fully responsible for DORA compliance despite the cloud provider's failure and supplies the audit, termination, and exit-strategy levers for the provider relationship going forward.",
        "strength": "moderate"
      },
      {
        "source_id": "dora",
        "source_short_name": "DORA",
        "article_number": 29,
        "recital_number": null,
        "annex_number": null,
        "section": "Managing of ICT third-party risk",
        "provision": "Article 29",
        "quote": "When performing the identification and assessment of risks referred to in Article 28(4), point (c), financial entities shall also take into account whether the envisaged conclusion of a contractual arrangement in relation to ICT services supporting critical or important functions would lead to any o...",
        "relevance": "Article 29's concentration-risk duties apply because the bank depends on a single cloud provider for critical online banking, requiring substitutability analysis and consideration of alternative solutions.",
        "strength": "weak"
      },
      {
        "source_id": "dora",
        "source_short_name": "DORA",
        "article_number": 30,
        "recital_number": null,
        "annex_number": null,
        "section": "Managing of ICT third-party risk",
        "provision": "Article 30",
        "quote": "The rights and obligations of the financial entity and of the ICT third-party service provider shall be clearly allocated and set out in writing. The full contract shall include the service level agreements and be documented in one written document which shall be available to the parties on paper, o...",
        "relevance": "Article 30 requires the cloud contract to secure incident assistance, notification of material developments, and tested contingency plans from the provider, the provisions the bank invokes during and after the outage.",
        "strength": "moderate"
      },
      {
        "source_id": "dora",
        "source_short_name": "DORA",
        "article_number": 22,
        "recital_number": null,
        "annex_number": null,
        "section": "ICT-related incident management, classification and reporting",
        "provision": "Article 22",
        "quote": "Without prejudice to the technical input, advice or remedies and subsequent follow-up which may be provided, where applicable, in accordance with national law, by the CSIRTs under Directive (EU) 2022/2555, the competent authority shall, upon receipt of the initial notification and of each report as ...",
        "relevance": "Article 22 provides that the bank remains fully responsible for the incident's handling and its consequences notwithstanding any supervisory feedback or guidance the competent authority gives on its notification and reports.",
        "strength": "weak"
      },
      {
        "source_id": "gdpr",
        "source_short_name": "GDPR",
        "article_number": 4,
        "recital_number": null,
        "annex_number": null,
        "section": "General Provisions",
        "provision": "Article 4",
        "quote": "For the purposes of this Regulation:",
        "relevance": "Article 4(12) frames the assessment of whether the outage also involved a personal data breach, which turns on whether client data were destroyed, lost, altered, disclosed, or accessed.",
        "strength": "weak"
      },
      {
        "source_id": "gdpr",
        "source_short_name": "GDPR",
        "article_number": 33,
        "recital_number": null,
        "annex_number": null,
        "section": "Security of Personal Data",
        "provision": "Article 33",
        "quote": "In the case of a personal data breach, the controller shall without undue delay and, where feasible, not later than 72 hours after having become aware of it, notify the personal data breach to the supervisory authority competent in accordance with Article 55, unless the personal data breach is unlik...",
        "relevance": "Article 33's 72-hour notification duty becomes live where the outage investigation reveals a personal data breach, an obligation the bank must keep in view alongside its DORA reporting.",
        "strength": "weak"
      },
      {
        "source_id": "gdpr",
        "source_short_name": "GDPR",
        "article_number": 34,
        "recital_number": null,
        "annex_number": null,
        "section": "Security of Personal Data",
        "provision": "Article 34",
        "quote": "When the personal data breach is likely to result in a high risk to the rights and freedoms of natural persons, the controller shall communicate the personal data breach to the data subject without undue delay. The communication to the data subject referred to in paragraph 1 of this Article shall de...",
        "relevance": "Article 34's communication duty attaches where the incident creates high risk to customers, complementing the DORA client notification for affected online-banking users.",
        "strength": "weak"
      },
      {
        "source_id": "gdpr",
        "source_short_name": "GDPR",
        "article_number": 58,
        "recital_number": null,
        "annex_number": null,
        "section": "Competence, Tasks and Powers",
        "provision": "Article 58",
        "quote": "Each supervisory authority shall have all of the following investigative powers: Each supervisory authority shall have all of the following corrective powers: Each supervisory authority shall have all of the following authorisation and advisory powers: The exercise of the powers conferred on the sup...",
        "relevance": "Article 58's corrective powers - ordering the breach's communication to data subjects, limiting or banning processing, and imposing administrative fines - hang over the conditional GDPR track the outage could open.",
        "strength": "weak"
      },
      {
        "source_id": "dora",
        "source_short_name": "DORA",
        "article_number": 16,
        "recital_number": null,
        "annex_number": null,
        "section": "ICT risk management",
        "provision": "Article 16",
        "quote": "Articles 5 to 15 of this Regulation shall not apply to small and non-interconnected investment firms, payment institutions exempted pursuant to Directive (EU) 2015/2366; institutions exempted pursuant to Directive 2013/36/EU in respect of which Member States have decided not to apply the option refe...",
        "relevance": "Article 16's simplified ICT risk-management framework is not open to a credit institution, so the bank must comply with the general framework of Articles 5 to 15, calibrating which obligations bite.",
        "strength": "weak"
      }
    ]
  },
  "trace": {
    "workflow": "planner -> researcher -> verifier -> proposer -> summarizer",
    "summary": "Planner identified ICT incident management and reporting, business continuity, third-party and concentration risk, and data protection as research targets; Researcher retrieved provisions from DORA and the GDPR; Verifier recorded each anticipated-but-unsupported claim as rejected \u2014 no Evidence in the Corpus supports it.",
    "unsupported_claims_discarded": [
      "The outage is automatically a personal data breach under the GDPR.",
      "DORA obliges the bank to compensate customers for losses caused by the outage.",
      "The DORA incident reports replace the GDPR's 72-hour breach notification.",
      "The bank may wait until the root cause is fully known before reporting the incident.",
      "The cloud provider, not the bank, is responsible for DORA compliance during the outage.",
      "The simplified ICT risk-management framework is available to the bank for this incident.",
      "Spain-specific supervisory requirements for incident reporting are covered by the corpus.",
      "The bank can exit the cloud contract without concentration-risk analysis or an exit strategy."
    ]
  },
  "detailed_trace": [
    {
      "step": "planner",
      "action": "identify topics: ICT incident management and major-incident reporting, business continuity and recovery, ICT third-party and concentration risk, GDPR breach readiness"
    },
    {
      "step": "researcher",
      "action": "retrieve incident-management, continuity, third-party, and data-protection provisions from DORA and the GDPR via corpus_lookup",
      "retrieved": [
        {
          "source_id": "dora",
          "kind": "article",
          "number": 17,
          "section": "ICT-related incident management, classification and reporting",
          "provision": "Article 17",
          "text": "Financial entities shall define, establish and implement an ICT-related incident management process to detect, manage and notify ICT-related incidents. Financial entities shall record all ICT-related incidents and significant cyber threats. Financial entities shall establish appropriate procedures and processes to ensure a consistent and integrated monitoring, handling and follow-up of ICT-related incidents, to ensure that root causes are identified, documented and addressed in order to prevent the occurrence of such incidents. The ICT-related incident management process referred to in paragraph 1 shall:"
        },
        {
          "source_id": "dora",
          "kind": "article",
          "number": 18,
          "section": "ICT-related incident management, classification and reporting",
          "provision": "Article 18",
          "text": "Financial entities shall classify ICT-related incidents and shall determine their impact based on the following criteria: Financial entities shall classify cyber threats as significant based on the criticality of the services at risk, including the financial entity's transactions and operations, number and/or relevance of clients or financial counterparts targeted and the geographical spread of the areas at risk. The ESAs shall, through the Joint Committee and in consultation with the ECB and ENISA, develop common draft regulatory technical standards further specifying the following: When developing the common draft regulatory technical standards referred to in paragraph 3 of this Article, the ESAs shall take into account the criteria set out in Article 4(2), as well as international standards, guidance and specifications developed and published by ENISA, including, where appropriate, specifications for other economic sectors. For the purposes of applying the criteria set out in Articl"
        },
        {
          "source_id": "dora",
          "kind": "article",
          "number": 19,
          "section": "ICT-related incident management, classification and reporting",
          "provision": "Article 19",
          "text": "Financial entities shall report major ICT-related incidents to the relevant competent authority as referred to in Article 46 in accordance with paragraph 4 of this Article. Where a financial entity is subject to supervision by more than one national competent authority referred to in Article 46, Member States shall designate a single competent authority as the relevant competent authority responsible for carrying out the functions and duties provided for in this Article. Credit institutions classified as significant, in accordance with Article 6(4) of Regulation (EU) No 1024/2013, shall report major ICT-related incidents to the relevant national competent authority designated in accordance with Article 4 of Directive 2013/36/EU, which shall immediately transmit that report to the ECB. For the purpose of the first subparagraph, financial entities shall produce, after collecting and analysing all relevant information, the initial notification and reports referred to in paragraph 4 of thi"
        },
        {
          "source_id": "dora",
          "kind": "article",
          "number": 11,
          "section": "ICT risk management",
          "provision": "Article 11",
          "text": "As part of the ICT risk management framework referred to in Article 6(1) and based on the identification requirements set out in Article 8, financial entities shall put in place a comprehensive ICT business continuity policy, which may be adopted as a dedicated specific policy, forming an integral part of the overall business continuity policy of the financial entity. Financial entities shall implement the ICT business continuity policy through dedicated, appropriate and documented arrangements, plans, procedures and mechanisms aiming to: As part of the ICT risk management framework referred to in Article 6(1), financial entities shall implement associated ICT response and recovery plans which, in the case of financial entities other than microenterprises, shall be subject to independent internal audit reviews. Financial entities shall put in place, maintain and periodically test appropriate ICT business continuity plans, notably with regard to critical or important functions outsource"
        },
        {
          "source_id": "dora",
          "kind": "article",
          "number": 12,
          "section": "ICT risk management",
          "provision": "Article 12",
          "text": "For the purpose of ensuring the restoration of ICT systems and data with minimum downtime, limited disruption and loss, as part of their ICT risk management framework, financial entities shall develop and document: Financial entities shall set up backup systems that can be activated in accordance with the backup policies and procedures, as well as restoration and recovery procedures and methods. The activation of backup systems shall not jeopardise the security of the network and information systems or the availability, authenticity, integrity or confidentiality of data. Testing of the backup procedures and restoration and recovery procedures and methods shall be undertaken periodically. When restoring backup data using own systems, financial entities shall use ICT systems that are physically and logically segregated from the source ICT system. The ICT systems shall be securely protected from any unauthorised access or ICT corruption and allow for the timely restoration of services mak"
        },
        {
          "source_id": "gdpr",
          "kind": "article",
          "number": 32,
          "section": "Security of Personal Data",
          "provision": "Article 32",
          "text": "Taking into account the state of the art, the costs of implementation and the nature, scope, context and purposes of processing as well as the risk of varying likelihood and severity for the rights and freedoms of natural persons, the controller and the processor shall implement appropriate technical and organisational measures to ensure a level of security appropriate to the risk, including inter alia as appropriate: (a) the pseudonymisation and encryption of personal data; (b) the ability to ensure the ongoing confidentiality, integrity, availability and resilience of processing systems and services; (c) the ability to restore the availability and access to personal data in a timely manner in the event of a physical or technical incident; (d) a process for regularly testing, assessing and evaluating the effectiveness of technical and organisational measures for ensuring the security of the processing. In assessing the appropriate level of security account shall be taken in particular"
        },
        {
          "source_id": "gdpr",
          "kind": "article",
          "number": 5,
          "section": "Principles",
          "provision": "Article 5",
          "text": "Personal data shall be: (a) processed lawfully, fairly and in a transparent manner in relation to the data subject ('lawfulness, fairness and transparency'); (b) collected for specified, explicit and legitimate purposes and not further processed in a manner that is incompatible with those purposes; further processing for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes shall, in accordance with Article 89(1), not be considered to be incompatible with the initial purposes ('purpose limitation'); (c) adequate, relevant and limited to what is necessary in relation to the purposes for which they are processed ('data minimisation'); (d) accurate and, where necessary, kept up to date; every reasonable step must be taken to ensure that personal data that are inaccurate, having regard to the purposes for which they are processed, are erased or rectified without delay ('accuracy'); (e) kept in a form which permits identification of da"
        },
        {
          "source_id": "gdpr",
          "kind": "article",
          "number": 6,
          "section": "Principles",
          "provision": "Article 6",
          "text": "Processing shall be lawful only if and to the extent that at least one of the following applies: (a) the data subject has given consent to the processing of his or her personal data for one or more specific purposes; (b) processing is necessary for the performance of a contract to which the data subject is party or in order to take steps at the request of the data subject prior to entering into a contract; (c) processing is necessary for compliance with a legal obligation to which the controller is subject; (d) processing is necessary in order to protect the vital interests of the data subject or of another natural person; (e) processing is necessary for the performance of a task carried out in the public interest or in the exercise of official authority vested in the controller; (f) processing is necessary for the purposes of the legitimate interests pursued by the controller or by a third party, except where such interests are overridden by the interests or fundamental rights and fre"
        },
        {
          "source_id": "gdpr",
          "kind": "article",
          "number": 24,
          "section": "General Obligations",
          "provision": "Article 24",
          "text": "Taking into account the nature, scope, context and purposes of processing as well as the risks of varying likelihood and severity for the rights and freedoms of natural persons, the controller shall implement appropriate technical and organisational measures to ensure and to be able to demonstrate that processing is performed in accordance with this Regulation. Those measures shall be reviewed and updated where necessary. Where proportionate in relation to processing activities, the measures referred to in paragraph 1 shall include the implementation of appropriate data protection policies by the controller. Adherence to approved codes of conduct as referred to in Article 40 or approved certification mechanisms as referred to in Article 42 may be used as an element by which to demonstrate compliance with the obligations of the controller."
        },
        {
          "source_id": "gdpr",
          "kind": "article",
          "number": 28,
          "section": "General Obligations",
          "provision": "Article 28",
          "text": "Where processing is to be carried out on behalf of a controller, the controller shall use only processors providing sufficient guarantees to implement appropriate technical and organisational measures in such a manner that processing will meet the requirements of this Regulation and ensure the protection of the rights of the data subject. The processor shall not engage another processor without prior specific or general written authorisation of the controller. In the case of general written authorisation, the processor shall inform the controller of any intended changes concerning the addition or replacement of other processors, thereby giving the controller the opportunity to object to such changes. Processing by a processor shall be governed by a contract or other legal act under Union or Member State law, that is binding on the processor with regard to the controller and that sets out the subject-matter and duration of the processing, the nature and purpose of the processing, the ty"
        },
        {
          "source_id": "dora",
          "kind": "article",
          "number": 8,
          "section": "ICT risk management",
          "provision": "Article 8",
          "text": "As part of the ICT risk management framework referred to in Article 6(1), financial entities shall identify, classify and adequately document all ICT supported business functions, roles and responsibilities, the information assets and ICT assets supporting those functions, and their roles and dependencies in relation to ICT risk. Financial entities shall review as needed, and at least yearly, the adequacy of this classification and of any relevant documentation. Financial entities shall, on a continuous basis, identify all sources of ICT risk, in particular the risk exposure to and from other financial entities, and assess cyber threats and ICT vulnerabilities relevant to their ICT supported business functions, information assets and ICT assets. Financial entities shall review on a regular basis, and at least yearly, the risk scenarios impacting them. Financial entities, other than microenterprises, shall perform a risk assessment upon each major change in the network and information s"
        },
        {
          "source_id": "dora",
          "kind": "article",
          "number": 5,
          "section": "ICT risk management",
          "provision": "Article 5",
          "text": "Financial entities shall have in place an internal governance and control framework that ensures an effective and prudent management of ICT risk, in accordance with Article 6(4), in order to achieve a high level of digital operational resilience. The management body of the financial entity shall define, approve, oversee and be responsible for the implementation of all arrangements related to the ICT risk management framework referred to in Article 6(1). For the purposes of the first subparagraph, the management body shall: Financial entities, other than microenterprises, shall establish a role in order to monitor the arrangements concluded with ICT third-party service providers on the use of ICT services, or shall designate a member of senior management as responsible for overseeing the related risk exposure and relevant documentation. Members of the management body of the financial entity shall actively keep up to date with sufficient knowledge and skills to understand and assess ICT "
        },
        {
          "source_id": "dora",
          "kind": "article",
          "number": 10,
          "section": "ICT risk management",
          "provision": "Article 10",
          "text": "Financial entities shall have in place mechanisms to promptly detect anomalous activities, in accordance with Article 17, including ICT network performance issues and ICT-related incidents, and to identify potential material single points of failure. All detection mechanisms referred to in the first subparagraph shall be regularly tested in accordance with Article 25. The detection mechanisms referred to in paragraph 1 shall enable multiple layers of control, define alert thresholds and criteria to trigger and initiate ICT-related incident response processes, including automatic alert mechanisms for relevant staff in charge of ICT-related incident response. Financial entities shall devote sufficient resources and capabilities to monitor user activity, the occurrence of ICT anomalies and ICT-related incidents, in particular cyber-attacks. Data reporting service providers shall, in addition, have in place systems that can effectively check trade reports for completeness, identify omissio"
        },
        {
          "source_id": "gdpr",
          "kind": "article",
          "number": 30,
          "section": "General Obligations",
          "provision": "Article 30",
          "text": "Each controller and, where applicable, the controller's representative, shall maintain a record of processing activities under its responsibility. That record shall contain all of the following information: (a) the name and contact details of the controller and, where applicable, the joint controller, the controller's representative and the data protection officer; (b) the purposes of the processing; (c) a description of the categories of data subjects and of the categories of personal data; (d) the categories of recipients to whom the personal data have been or will be disclosed including recipients in third countries or international organisations; (e) where applicable, transfers of personal data to a third country or an international organisation, including the identification of that third country or international organisation and, in the case of transfers referred to in the second subparagraph of Article 49(1), the documentation of suitable safeguards; (f) where possible, the envis"
        },
        {
          "source_id": "dora",
          "kind": "article",
          "number": 2,
          "section": "General provisions",
          "provision": "Article 2",
          "text": "Without prejudice to paragraphs 3 and 4, this Regulation applies to the following entities: For the purposes of this Regulation, entities referred to in paragraph 1, points (a) to (t), shall collectively be referred to as 'financial entities'. This Regulation does not apply to: Member States may exclude from the scope of this Regulation entities referred to in Article 2(5), points (4) to (23), of Directive 2013/36/EU that are located within their respective territories. Where a Member State makes use of such option, it shall inform the Commission thereof as well as of any subsequent changes thereto. The Commission shall make that information publicly available on its website or other easily accessible means."
        },
        {
          "source_id": "dora",
          "kind": "article",
          "number": 3,
          "section": "General provisions",
          "provision": "Article 3",
          "text": "For the purposes of this Regulation, the following definitions shall apply:"
        },
        {
          "source_id": "dora",
          "kind": "article",
          "number": 4,
          "section": "General provisions",
          "provision": "Article 4",
          "text": "Financial entities shall implement the rules laid down in Chapter II in accordance with the principle of proportionality, taking into account their size and overall risk profile, and the nature, scale and complexity of their services, activities and operations. In addition, the application by financial entities of Chapters III, IV and V, Section I, shall be proportionate to their size and overall risk profile, and to the nature, scale and complexity of their services, activities and operations, as specifically provided for in the relevant rules of those Chapters. The competent authorities shall consider the application of the proportionality principle by financial entities when reviewing the consistency of the ICT risk management framework on the basis of the reports submitted upon the request of competent authorities pursuant to Article 6(5) and Article 16(2). ---"
        },
        {
          "source_id": "dora",
          "kind": "article",
          "number": 6,
          "section": "ICT risk management",
          "provision": "Article 6",
          "text": "Financial entities shall have a sound, comprehensive and well-documented ICT risk management framework as part of their overall risk management system, which enables them to address ICT risk quickly, efficiently and comprehensively and to ensure a high level of digital operational resilience. The ICT risk management framework shall include at least strategies, policies, procedures, ICT protocols and tools that are necessary to duly and adequately protect all information assets and ICT assets, including computer software, hardware, servers, as well as to protect all relevant physical components and infrastructures, such as premises, data centres and sensitive designated areas, to ensure that all information assets and ICT assets are adequately protected from risks including damage and unauthorised access or usage. In accordance with their ICT risk management framework, financial entities shall minimise the impact of ICT risk by deploying appropriate strategies, policies, procedures, ICT"
        },
        {
          "source_id": "dora",
          "kind": "article",
          "number": 13,
          "section": "ICT risk management",
          "provision": "Article 13",
          "text": "Financial entities shall have in place capabilities and staff to gather information on vulnerabilities and cyber threats, ICT-related incidents, in particular cyber-attacks, and analyse the impact they are likely to have on their digital operational resilience. Financial entities shall put in place post ICT-related incident reviews after a major ICT-related incident disrupts their core activities, analysing the causes of disruption and identifying required improvements to the ICT operations or within the ICT business continuity policy referred to in Article 11. Financial entities, other than microenterprises, shall, upon request, communicate to the competent authorities, the changes that were implemented following post ICT-related incident reviews as referred to in the first subparagraph. The post ICT-related incident reviews referred to in the first subparagraph shall determine whether the established procedures were followed and the actions taken were effective, including in relation"
        },
        {
          "source_id": "dora",
          "kind": "article",
          "number": 14,
          "section": "ICT risk management",
          "provision": "Article 14",
          "text": "As part of the ICT risk management framework referred to in Article 6(1), financial entities shall have in place crisis communication plans enabling a responsible disclosure of, at least, major ICT-related incidents or vulnerabilities to clients and counterparts as well as to the public, as appropriate. As part of the ICT risk management framework, financial entities shall implement communication policies for internal staff and for external stakeholders. Communication policies for staff shall take into account the need to differentiate between staff involved in ICT risk management, in particular the staff responsible for response and recovery, and staff that needs to be informed. At least one person in the financial entity shall be tasked with implementing the communication strategy for ICT-related incidents and fulfil the public and media function for that purpose."
        },
        {
          "source_id": "dora",
          "kind": "article",
          "number": 28,
          "section": "Managing of ICT third-party risk",
          "provision": "Article 28",
          "text": "Financial entities shall manage ICT third-party risk as an integral component of ICT risk within their ICT risk management framework as referred to in Article 6(1), and in accordance with the following principles: As part of their ICT risk management framework, financial entities, other than entities referred to in Article 16(1), first subparagraph, and other than microenterprises, shall adopt, and regularly review, a strategy on ICT third-party risk, taking into account the multi-vendor strategy referred to in Article 6(9), where applicable. The strategy on ICT third-party risk shall include a policy on the use of ICT services supporting critical or important functions provided by ICT third-party service providers and shall apply on an individual basis and, where relevant, on a sub-consolidated and consolidated basis. The management body shall, on the basis of an assessment of the overall risk profile of the financial entity and the scale and complexity of the business services, regul"
        },
        {
          "source_id": "dora",
          "kind": "article",
          "number": 29,
          "section": "Managing of ICT third-party risk",
          "provision": "Article 29",
          "text": "When performing the identification and assessment of risks referred to in Article 28(4), point (c), financial entities shall also take into account whether the envisaged conclusion of a contractual arrangement in relation to ICT services supporting critical or important functions would lead to any of the following: Where the contractual arrangements on the use of ICT services supporting critical or important functions include the possibility that an ICT third-party service provider further subcontracts ICT services supporting a critical or important function to other ICT third-party service providers, financial entities shall weigh benefits and risks that may arise in connection with such subcontracting, in particular in the case of an ICT subcontractor established in a third-country. Where contractual arrangements concern ICT services supporting critical or important functions, financial entities shall duly consider the insolvency law provisions that would apply in the event of the IC"
        },
        {
          "source_id": "dora",
          "kind": "article",
          "number": 30,
          "section": "Managing of ICT third-party risk",
          "provision": "Article 30",
          "text": "The rights and obligations of the financial entity and of the ICT third-party service provider shall be clearly allocated and set out in writing. The full contract shall include the service level agreements and be documented in one written document which shall be available to the parties on paper, or in a document with another downloadable, durable and accessible format. The contractual arrangements on the use of ICT services shall include at least the following elements: The contractual arrangements on the use of ICT services supporting critical or important functions shall include, in addition to the elements referred to in paragraph 2, at least the following: When negotiating contractual arrangements, financial entities and ICT third-party service providers shall consider the use of standard contractual clauses developed by public authorities for specific services. The ESAs shall, through the Joint Committee, develop draft regulatory technical standards to specify further the elemen"
        },
        {
          "source_id": "dora",
          "kind": "article",
          "number": 22,
          "section": "ICT-related incident management, classification and reporting",
          "provision": "Article 22",
          "text": "Without prejudice to the technical input, advice or remedies and subsequent follow-up which may be provided, where applicable, in accordance with national law, by the CSIRTs under Directive (EU) 2022/2555, the competent authority shall, upon receipt of the initial notification and of each report as referred to in Article 19(4), acknowledge receipt and may, where feasible, provide in a timely manner relevant and proportionate feedback or high-level guidance to the financial entity, in particular by making available any relevant anonymised information and intelligence on similar threats, and may discuss remedies applied at the level of the financial entity and ways to minimise and mitigate adverse impact across the financial sector. Without prejudice to the supervisory feedback received, financial entities shall remain fully responsible for the handling and for consequences of the ICT-related incidents reported pursuant to Article 19(1). The ESAs shall, through the Joint Committee, on an"
        },
        {
          "source_id": "gdpr",
          "kind": "article",
          "number": 4,
          "section": "General Provisions",
          "provision": "Article 4",
          "text": "For the purposes of this Regulation:"
        },
        {
          "source_id": "gdpr",
          "kind": "article",
          "number": 33,
          "section": "Security of Personal Data",
          "provision": "Article 33",
          "text": "In the case of a personal data breach, the controller shall without undue delay and, where feasible, not later than 72 hours after having become aware of it, notify the personal data breach to the supervisory authority competent in accordance with Article 55, unless the personal data breach is unlikely to result in a risk to the rights and freedoms of natural persons. Where the notification to the supervisory authority is not made within 72 hours, it shall be accompanied by reasons for the delay. The processor shall notify the controller without undue delay after becoming aware of a personal data breach. The notification referred to in paragraph 1 shall at least: (a) describe the nature of the personal data breach including where possible, the categories and approximate number of data subjects concerned and the categories and approximate number of personal data records concerned; (b) communicate the name and contact details of the data protection officer or other contact point where mo"
        },
        {
          "source_id": "gdpr",
          "kind": "article",
          "number": 34,
          "section": "Security of Personal Data",
          "provision": "Article 34",
          "text": "When the personal data breach is likely to result in a high risk to the rights and freedoms of natural persons, the controller shall communicate the personal data breach to the data subject without undue delay. The communication to the data subject referred to in paragraph 1 of this Article shall describe in clear and plain language the nature of the personal data breach and contain at least the information and measures referred to in points (b), (c) and (d) of Article 33(3). The communication to the data subject referred to in paragraph 1 shall not be required if any of the following conditions are met: (a) the controller has implemented appropriate technical and organisational protection measures, and those measures were applied to the personal data affected by the personal data breach, in particular those that render the personal data unintelligible to any person who is not authorised to access it, such as encryption; (b) the controller has taken subsequent measures which ensure tha"
        },
        {
          "source_id": "gdpr",
          "kind": "article",
          "number": 58,
          "section": "Competence, Tasks and Powers",
          "provision": "Article 58",
          "text": "Each supervisory authority shall have all of the following investigative powers: Each supervisory authority shall have all of the following corrective powers: Each supervisory authority shall have all of the following authorisation and advisory powers: The exercise of the powers conferred on the supervisory authority pursuant to this Article shall be subject to appropriate safeguards, including effective judicial remedy and due process, set out in Union and Member\u00a0State law in accordance with the Charter. Each Member\u00a0State shall provide by law that its supervisory authority shall have the power to bring infringements of this Regulation to the attention of the judicial authorities and where appropriate, to commence or engage otherwise in legal proceedings, in order to enforce the provisions of this Regulation. Each Member State may provide by law that its supervisory authority shall have additional powers to those referred to in paragraphs\u00a01, 2 and 3. The exercise of those powers shall "
        },
        {
          "source_id": "dora",
          "kind": "article",
          "number": 16,
          "section": "ICT risk management",
          "provision": "Article 16",
          "text": "Articles 5 to 15 of this Regulation shall not apply to small and non-interconnected investment firms, payment institutions exempted pursuant to Directive (EU) 2015/2366; institutions exempted pursuant to Directive 2013/36/EU in respect of which Member States have decided not to apply the option referred to in Article 2(4) of this Regulation; electronic money institutions exempted pursuant to Directive 2009/110/EC; and small institutions for occupational retirement provision. Without prejudice to the first subparagraph, the entities listed in the first subparagraph shall: The ICT risk management framework referred to in paragraph 1, second subparagraph, point (a), shall be documented and reviewed periodically and upon the occurrence of major ICT-related incidents in compliance with supervisory instructions. It shall be continuously improved on the basis of lessons derived from implementation and monitoring. A report on the review of the ICT risk management framework shall be submitted t"
        }
      ],
      "tool_calls": [
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "dora",
            "kind": "article",
            "number": 17
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "dora",
            "kind": "article",
            "number": 18
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "dora",
            "kind": "article",
            "number": 19
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "dora",
            "kind": "article",
            "number": 11
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "dora",
            "kind": "article",
            "number": 12
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "gdpr",
            "kind": "article",
            "number": 32
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "gdpr",
            "kind": "article",
            "number": 5
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "gdpr",
            "kind": "article",
            "number": 6
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "gdpr",
            "kind": "article",
            "number": 24
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "gdpr",
            "kind": "article",
            "number": 28
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "dora",
            "kind": "article",
            "number": 8
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "dora",
            "kind": "article",
            "number": 5
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "dora",
            "kind": "article",
            "number": 10
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "gdpr",
            "kind": "article",
            "number": 30
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "dora",
            "kind": "article",
            "number": 2
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "dora",
            "kind": "article",
            "number": 3
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "dora",
            "kind": "article",
            "number": 4
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "dora",
            "kind": "article",
            "number": 6
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "dora",
            "kind": "article",
            "number": 13
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "dora",
            "kind": "article",
            "number": 14
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "dora",
            "kind": "article",
            "number": 28
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "dora",
            "kind": "article",
            "number": 29
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "dora",
            "kind": "article",
            "number": 30
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "dora",
            "kind": "article",
            "number": 22
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "gdpr",
            "kind": "article",
            "number": 4
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "gdpr",
            "kind": "article",
            "number": 33
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "gdpr",
            "kind": "article",
            "number": 34
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "gdpr",
            "kind": "article",
            "number": 58
          },
          "status": "found"
        },
        {
          "tool": "corpus_lookup",
          "input": {
            "source_id": "dora",
            "kind": "article",
            "number": 16
          },
          "status": "found"
        }
      ]
    },
    {
      "step": "verifier",
      "action": "record the curated anticipated-but-unsupported claims as rejected (no Evidence in the Corpus supports this claim) and tag each finding with its evidence strength",
      "claim_decisions": [
        {
          "claim": "The outage is automatically a personal data breach under the GDPR.",
          "status": "rejected",
          "reason": "no Evidence in the Corpus supports this claim",
          "dropped_refs": []
        },
        {
          "claim": "DORA obliges the bank to compensate customers for losses caused by the outage.",
          "status": "rejected",
          "reason": "no Evidence in the Corpus supports this claim",
          "dropped_refs": []
        },
        {
          "claim": "The DORA incident reports replace the GDPR's 72-hour breach notification.",
          "status": "rejected",
          "reason": "no Evidence in the Corpus supports this claim",
          "dropped_refs": []
        },
        {
          "claim": "The bank may wait until the root cause is fully known before reporting the incident.",
          "status": "rejected",
          "reason": "no Evidence in the Corpus supports this claim",
          "dropped_refs": []
        },
        {
          "claim": "The cloud provider, not the bank, is responsible for DORA compliance during the outage.",
          "status": "rejected",
          "reason": "no Evidence in the Corpus supports this claim",
          "dropped_refs": []
        },
        {
          "claim": "The simplified ICT risk-management framework is available to the bank for this incident.",
          "status": "rejected",
          "reason": "no Evidence in the Corpus supports this claim",
          "dropped_refs": []
        },
        {
          "claim": "Spain-specific supervisory requirements for incident reporting are covered by the corpus.",
          "status": "rejected",
          "reason": "no Evidence in the Corpus supports this claim",
          "dropped_refs": []
        },
        {
          "claim": "The bank can exit the cloud contract without concentration-risk analysis or an exit strategy.",
          "status": "rejected",
          "reason": "no Evidence in the Corpus supports this claim",
          "dropped_refs": []
        }
      ]
    },
    {
      "step": "summarizer",
      "action": "serve the locked Provision relevance and rated Citation strength for each cited provision from the demo content",
      "summary_decisions": []
    }
  ],
  "known_limitations": [
    "Known limitation: the corpus is English-only; questions in other languages are answered in English.",
    "Known limitation: Regula is a research prototype, not legal advice; answers require verification by a qualified professional."
  ]
};

export const insufficientEvidenceResponse: AnalyzeResponse = {
  "answer": {
    "findings": [],
    "actions": [
      "Rephrase the Regulatory question using the vocabulary of the Corpus \u2014 EU AI Act, GDPR, or DORA terms such as 'high-risk AI system', 'automated decision-making', or 'ICT third-party risk'.",
      "Check whether the obligation you are asking about falls outside the Corpus (e.g. national requirements of a single member state)."
    ],
    "citations": []
  },
  "trace": {
    "workflow": "planner -> researcher -> verifier -> proposer -> summarizer",
    "summary": "Planner identified research targets (employment-law obligations for Spanish restaurant booking software); retrieval returned no Chunks relevant enough, so no Claims were drafted or verified \u2014 the Corpus holds nothing for this question.",
    "unsupported_claims_discarded": []
  },
  "detailed_trace": [
    {
      "step": "planner",
      "action": "decompose the Regulatory question into research targets",
      "research_targets": [
        "employment-law obligations for Spanish restaurant booking software"
      ]
    },
    {
      "step": "researcher",
      "action": "retrieve Evidence exclusively via the retrieve_chunks tool, then draft Claims grounded in it",
      "retrieved": [],
      "tool_calls": []
    },
    {
      "step": "verifier",
      "action": "check each Claim against the retrieved Evidence, judge its support and materiality, tag its Strength, and discard Unsupported and Immaterial claims",
      "claim_decisions": []
    },
    {
      "step": "proposer",
      "action": "no Evidence was retrieved: the Insufficient-evidence path was served and the Proposer made no LLM call",
      "action_decisions": []
    },
    {
      "step": "summarizer",
      "action": "no cited provision needed a relevance statement, and no LLM call was made",
      "summary_decisions": []
    }
  ],
  "known_limitations": [
    "Known limitation: the corpus is English-only; questions in other languages are answered in English.",
    "Known limitation: Regula is a research prototype, not legal advice; answers require verification by a qualified professional.",
    "Known limitation: the Corpus holds nothing relevant enough to answer this question, so no Findings were produced."
  ]
};

export const notAvailableResponse: AnalyzeResponse = {
  "answer": {
    "findings": [],
    "actions": [
      "The Corpus is not ingested yet, so Live mode has nothing to retrieve from.",
      "Ingest it once with: python -m backend.src.ingest",
      "Inside the Docker stack, run: docker compose exec backend python -m backend.src.ingest",
      "Ingestion takes effect immediately \u2014 re-run your request afterwards; no restart is needed.",
      "Re-run with mode 'demo' to analyze the canonical bank cloud outage scenario via scenario.id 'bank-cloud-outage'."
    ],
    "citations": []
  },
  "trace": {
    "workflow": "not-available",
    "summary": "Live mode selected but the vector store is empty; no retrieval performed.",
    "unsupported_claims_discarded": []
  },
  "detailed_trace": [],
  "known_limitations": [
    "Known limitation: the corpus is English-only; questions in other languages are answered in English."
  ]
};

// The Not-available response a custom Scenario receives in Demo mode: the
// canonical scenario is the only one Demo serves (ADR-0005), and the reply
// hints at the demo button (issue #48).
export const demoNotAvailableResponse: AnalyzeResponse = {
  "answer": {
    "findings": [],
    "actions": [
      "The deterministic demo currently supports one scenario: use scenario.id 'bank-cloud-outage' with the bank cloud outage question.",
      "In the web UI, use the 'Try the demo scenario' button to fill the form with the canonical scenario, then Analyze.",
      "This demo covers DORA (ICT incident management, third-party risk) and the GDPR (security of processing, breach notification) for a cloud outage at a bank."
    ],
    "citations": []
  },
  "trace": {
    "workflow": "noop",
    "summary": "No demo match; no retrieval performed. Provide scenario.id 'bank-cloud-outage' to invoke the demo.",
    "unsupported_claims_discarded": []
  },
  "detailed_trace": [],
  "known_limitations": [
    "Known limitation: the corpus is English-only; questions in other languages are answered in English.",
    "Known limitation: Regula is a research prototype, not legal advice; answers require verification by a qualified professional."
  ]
};
